### ISSUE TITLE
Unable to Connect API on Android App

### ISSUE THREAD

**Issue by jaypatel9244** [leoliew/magento-api#3]
Hello,
I am unable to connect the API on android application.
The customer ID is taken from web frontend cookie, So unable to connect it on android app.

**Comment by leoliew** [comment]
you can set customer'id to your cookie in android app

**Comment by jaypatel9244** [comment]
Can you please show a demo code of android app?
It would be very help full form me.
After customer login API I am trying to get the addresslist of a customer but it is showing me 'User not logged in'.

**Comment by leoliew** [comment]
if you use apache http package
like this

```
import org.apache.http.client.methods.HttpGet;
HttpGet httpGet = new HttpGet(uri);
httpGet.setHeader("Cookie", "frontend="+SESSIONID);  
```

**Comment by leoliew** [comment]
@jaypatel9244

**Comment by jaypatel9244** [comment]
Thank you so much mate. :+1:

**Comment by winnerawan** [comment]
@jaypatel9244 work with me , what library that your use ?
