### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by winnerawan** [leoliew/magento-api#4]
i have implemented login and this is response from header 
`COOK 1 = {Cache-Control=no-store, no-cache, must-revalidate, post-check=0, pre-check=0, Connection=Keep-Alive, Content-Type=text/html; charset=UTF-8, Date=Sun, 09 Oct 2016 23:06:31 GMT, Expires=Thu, 19 Nov 1981 08:52:00 GMT, Keep-Alive=timeout=5, max=100, Pragma=no-cache, Server=Apache/2.4.10 (Ubuntu), Set-Cookie=frontend=971k6rmbv6lsurkj3b43gcgiq2; expires=Mon, 10-Oct-2016 00:06:31 GMT; Max-Age=3600; path=/kopma; domain=76.164.195.171; HttpOnly, Vary=Accept-Encoding, X-Android-Received-Millis=1476054391995, X-Android-Response-Source=NETWORK 200, X-Android-Selected-Protocol=http/1.1, X-Android-Sent-Millis=1476054390660, X-Frame-Options=SAMEORIGIN}`

and also i get response 
`{"code":0,"msg":null,"model":{"entity_id":"5","name":"President X","email":"president@gmail.com","avatar":null,"tel":null,"session":"6ajn239fgft8cb4vs9b2gicpe6"}}`

but when i check user status i got message `not user login`
why ? some help please, sorry for english

**Comment by leoliew** [comment]
When you request the api that need login , the request inside to add a cookie data, key name  "frontend" , the value of the session after that return of the login api's session value

**Comment by winnerawan** [comment]
@leoliew can you give me an example just for login using retrofit or volley ? session value is cookies value right ? i'm stuck , please
or tell me step by step

so basically what i've done is 
1. Call login post login request, it return to me something like this
`{"code":0,"msg":null,"model":{"entity_id":"5","name":"President X","email":"president@gmail.com","avatar":null,"tel":null,"session":"6ajn239fgft8cb4vs9b2gicpe6"}}`
2. i think that value is i success login so i save that value to sql db and pass to main activity
3. on main activity i check user status, but not login , where the problem

http://github.com/winnerawan/kopma

**Comment by leoliew** [comment]
your login success  , in your android project ,if you use apache http package for your check user status api , like this : 

```
import org.apache.http.client.methods.HttpGet;
HttpGet httpGet = new HttpGet(uri);
httpGet.setHeader("Cookie", "frontend="+SESSIONID);  
```

SESSIONID is The value returned by the first step response's session

**Comment by winnerawan** [comment]
@leoliew  thanks you for fast response, httpget is deprectaed on api 23, is that now other method using retrofit or volley for this problem ? 
you said my login success but i cant add product to cart

**Comment by leoliew** [comment]
because your cant set cookies in your request , You can look at the request log in  server to see if they can receive cookies data

**Comment by winnerawan** [comment]
if i use apache http package can i post request to add product to cart ? and get the return value ?
some example maybe

**Comment by leoliew** [comment]
yes , you can try this api with some http tools ,like postman .

**Comment by winnerawan** [comment]
yes, this api work in postman, need some example check user status and then give the log if the use success login (null message)

**Comment by ujjwalsahay** [comment]
Hi @winnerawan @leoliew How did you passed cookie in header and what library you used, i am using retrofit. Please guide me how to do that in retrofit or volley.

**Comment by winnerawan** [comment]
@ujjwalsahay i dont use retrofit anymore, but last year when i try this api i use retrofit 1.9

```java
RestAdapter restAdapter = new RestAdapter.Builder()
                .setRequestInterceptor(new RequestInterceptor() {
                    @Override
                    public void intercept(RequestInterceptor.RequestFacade request) {
                        request.addHeader("Cookie", "frontend=" + session);
                    }
                })
                .setEndpoint(URL).build();
```

session is return value when you login, save it on db or sharedpreference and use it for every request that need cookie

**Comment by ujjwalsahay** [comment]
@leoliew Where is forgot password api ? i am able to fine only update password api. But i am looking for forgot password api.
