### ISSUE TITLE
Product list

### ISSUE THREAD

**Issue by deviggner** [leoliew/magento-api#8]
Hello @leoliew 

Thank you for this great repository. I would like to ask, is there an endpoint for product list with categories in your api?

**Comment by leoliew** [comment]
get products by category id :  
https://github.com/leoliew/magento-api/blob/master/api/en/index.md#catelogSale

**Comment by ilyasdogruer** [comment]
Thank you @leoliew 

One more question; i would like to load all categories with an endpoint. I can do this with 

`/mobileapi/index/index?cmd=menu
`

But this endpoint does not load the categories which does not contain any product. How can load all of them, even with zero product categories?

**Comment by deviggner** [comment]
Thank you @leoliew

One more question; i would like to load all categories with an endpoint. I can do this with

`/mobileapi/index/index?cmd=menu
`

But this endpoint does not load the categories which does not contain any product. How can load all of them, even with zero product categories?
